{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744963342\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x00000214B025F050>\nuser_page = <pages.user_page.UserPage object at 0x00000214B016F530>\ncreated_user = <config.data.user_data object at 0x00000214B030C5C0>\n\n    def test_login_with_wrong_data(self, user_page, created_user):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            print(\"Вход в систему с недействительными учетными данными...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Пароль: wrongpassword123\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword123\")\n    \n            print(f\"HTTP статус код ответа: {response.status_code}\")\n            print(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n>           assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\nE           AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744963342\"}\nE           assert 200 == 400\nE            +  where 200 = <Response [200]>.status_code\n\ntest_user_operations.py:187: AssertionError"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744963342\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 187, in test_login_with_wrong_data\n    assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "8eb14276-28b5-45ce-8c28-d0779ec1ba96-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "d8f8b95d-b7da-427d-8702-8420b69e6464-attachment.json", "type": "application/json"}], "start": 1719744964384, "stop": 1719744964385}], "start": 1719744963271, "stop": 1719744964385}], "attachments": [{"name": "stdout", "source": "a6ea3c35-6d09-46c4-b94e-0ccb8d965e57-attachment.txt", "type": "text/plain"}], "start": 1719744963271, "stop": 1719744964386, "uuid": "00c836f6-6d45-4574-8658-ec7a0e126961", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "7876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}