{"name": "test_create_user_with_existing_username", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'id'", "trace": "@pytest.fixture(scope=\"module\")\n    def user_data():\n>       return generate_user_data()\n\n..\\conftest.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def generate_user_data():\n        user = \"user1\"\n>       user.id = generate_id()\nE       AttributeError: 'str' object has no attribute 'id'\n\n..\\config\\generator.py:34: AttributeError"}, "start": 1719729919593, "stop": 1719729919593, "uuid": "679b62c7-37bb-432c-b154-b021c52e11bd", "historyId": "aa777f2a8ec599012f35bf2a809c5310", "testCaseId": "aa777f2a8ec599012f35bf2a809c5310", "fullName": "tests.test_user_operations.TestUserOperations#test_create_user_with_existing_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "7900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}