{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719745260071\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x000001E4BE4235C0>\nuser_page = <pages.user_page.UserPage object at 0x000001E4BE43CA10>\ncreated_user = <config.data.user_data object at 0x000001E4BE43C9B0>\n\n    def test_login_with_wrong_data(self, user_page, created_user):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            print(\"Вход в систему с недействительными учетными данными...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Пароль: wrongpassword123\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword123\")\n    \n            print(f\"HTTP статус код ответа: {response.status_code}\")\n            print(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n>           assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\nE           AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719745260071\"}\nE           assert 200 == 400\nE            +  where 200 = <Response [200]>.status_code\n\ntest_user_operations.py:187: AssertionError"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый 400ый статус код, но получен 200. Ответ: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719745260071\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 187, in test_login_with_wrong_data\n    assert response.status_code == 400, f\"Ожидаемый 400ый статус код, но получен {response.status_code}. Ответ: {response.text}\"\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "f9369e39-a319-4fbf-8485-bced4212fdd6-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "0ee1943d-bfc9-4cc5-b921-5da57f0fff9d-attachment.json", "type": "application/json"}], "start": 1719745261110, "stop": 1719745261111}], "start": 1719745260030, "stop": 1719745261111}], "attachments": [{"name": "stdout", "source": "4c93e7bc-1497-4cc7-9792-182bc181fe3a-attachment.txt", "type": "text/plain"}], "start": 1719745260030, "stop": 1719745261112, "uuid": "3d2f49bb-7ac3-4fec-b4c7-a8eec59358ad", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "3692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}