{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "0371b5ac-52d7-43f9-8170-57eb9f29c453-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "96ff3721-a205-4c5a-bab7-4c49dd707b34-attachment.json", "type": "application/json"}], "start": 1719742130840, "stop": 1719742130841}], "start": 1719742129731, "stop": 1719742130841}], "start": 1719742129731, "stop": 1719742130841, "uuid": "6eaae9f0-21af-4672-a4e0-a524dd038f68", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}