{"name": "test_create_user_with_existing_username", "status": "broken", "statusDetails": {"message": "TypeError: User() takes no arguments", "trace": "cls = <class 'tests.test_user_operations.TestUserAPI'>\n\n    @classmethod\n    def setup_class(cls):\n        cls.user_page = UserPage()\n>       cls.user_data = generate_user().__dict__\n\ntest_user_operations.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def generate_user():\n>       return User(\n            id=random.randint(1, 100),\n            username=fake.user_name(),\n            firstName=fake.first_name(),\n            lastName=fake.last_name(),\n            email=fake.safe_email(),\n            password=fake.password(),\n            phone=\"+7922964\" + ''.join(random.choices(string.digits, k=4)),\n            userStatus=random.randint(0, 100)\n        )\nE       TypeError: User() takes no arguments\n\n..\\config\\generator.py:8: TypeError"}, "start": 1719518114789, "stop": 1719518114789, "uuid": "bdec1f6e-475f-4ae1-84af-fdf2b2f6f30e", "historyId": "5190491c7ca640039e398046999456d5", "testCaseId": "5190491c7ca640039e398046999456d5", "fullName": "tests.test_user_operations.TestUserAPI#test_create_user_with_existing_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "18616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}